### ISSUE TITLE
assertArrayLength throws exception in multi-thread

### ISSUE THREAD

**Issue by sky4star** [raydac/java-binary-block-parser#10]
Hi @raydac ,

First of all, thanks for such a brilliant parser, it is very helpful! I am using it to parse TCP packets in Spark streaming. 

Currently, i notice JBBP throws parsing exception occasionally when running in multithread, while the same program works well in single thread. And if i copy the failed packet to unit test, it also passes. Would you mind taking a look?

My IP/TCP structure definition is: 
```
"skip:14; // skip bytes till the frame\n"
            +"bit:4 InternetHeaderLength;"
            +"bit:4 Version;"
            +"bit:2 ECN;"
            +"bit:6 DSCP;"
            +"ushort TotalPacketLength;"
            +"ushort Identification;"
            +"bit:8 IPFlagsAndFragmentOffset_low;"
            +"bit:5 IPFlagsAndFragmentOffset_high;"
            +"bit:1 MoreFragment;"
            +"bit:1 DonotFragment;"
            +"bit:1 ReservedBit;"
            +"ubyte TTL;"
            +"ubyte Protocol;"
            +"ushort HeaderChecksum;"
            +"int SourceAddress;"
            +"int DestinationAddress;"
            +"byte [(InternetHeaderLength-5)*4] Options;"

"skip:34; // skip bytes till the frame\n"
            + "ushort SourcePort;"
            + "ushort DestinationPort;"
            + "int SequenceNumber;"
            + "int AcknowledgementNumber;"
            + "bit:1 NONCE;"
            + "bit:3 RESERVED;"
            + "bit:4 HLEN;"
            + "bit:1 FIN;"
            + "bit:1 SYN;"
            + "bit:1 RST;"
            + "bit:1 PSH;"
            + "bit:1 ACK;"
            + "bit:1 URG;"
            + "bit:1 ECNECHO;"
            + "bit:1 CWR;"
            + "ushort WindowSize;"
            + "ushort TCPCheckSum;"
            + "ushort UrgentPointer;"
            + "byte [HLEN*4-20] Option;"
            + "byte [_] Data;"
```

And the exception i got is:
```
com.igormaznitsa.jbbp.exceptions.JBBPParsingException: Detected negative calculated array length for field 'options' [-80 (0xFFFFFFB0)]
     at com.igormaznitsa.jbbp.JBBPParser.assertArrayLength(JBBPParser.java:101)
     at com.igormaznitsa.jbbp.JBBPParser.parseStruct(JBBPParser.java:176)
     at com.igormaznitsa.jbbp.JBBPParser.parse(JBBPParser.java:489)
     at com.igormaznitsa.jbbp.JBBPParser.parse(JBBPParser.java:515)
``` 

and 
```
JBBPParsingException while parsing, Detected negative calculated array length for field 'option' [-68 (0xFFFFFFBC)]
```

Thanks in advance!

**Comment by raydac** [comment]
interesting, the parser is stateless and it doesn't share its state during parsing, is it possible that you make reading of data from the same input stream in another thread simultaneously?

**Comment by raydac** [comment]
yep, I can reproduce it, will investigate

**Comment by raydac** [comment]
I have fixed the issue, it was for non thread-safe behaviour of expression calculator

**Comment by sky4star** [comment]
So quick! Thank you so much!

**Comment by jobpav1984** [comment]
Hi! Thanx for this parser! It is brilliant! But i have same bug in version 1.3.0. There is I want implement VpnService in Andriod application for analyse traffic. But when application go to background state(foreground service) I had this exception: 
`03-21 18:08:35.342 2982-3025/ru.alexey.perelygin.trafficinspector E/AndroidRuntime: FATAL EXCEPTION: Thread-4
                                                                                    Process: ru.alexey.perelygin.trafficinspector, PID: 2982
                                                                                    com.igormaznitsa.jbbp.exceptions.JBBPParsingException: Detected negative calculated array length for field 'options' [-4 (0xFFFFFFFC)]
                                                                                        at com.igormaznitsa.jbbp.JBBPParser.assertArrayLength(JBBPParser.java:109)
                                                                                        at com.igormaznitsa.jbbp.JBBPParser.parseStruct(JBBPParser.java:272)
                                                                                        at com.igormaznitsa.jbbp.JBBPParser.parse(JBBPParser.java:570)
                                                                                        at com.igormaznitsa.jbbp.JBBPParser.parse(JBBPParser.java:541)
                                                                                        at ru.alexey.perelygin.trafficinspector.ui.TrafficInspectorVpnService.vpnLoop(TrafficInspectorVpnService.java:197)
                                                                                        at ru.alexey.perelygin.trafficinspector.ui.TrafficInspectorVpnService.bridge$lambda$0$TrafficInspectorVpnService(Unknown Source:0)
                                                                                        at ru.alexey.perelygin.trafficinspector.ui.TrafficInspectorVpnService$$Lambda$0.run(Unknown Source:0)
                                                                                        at java.lang.Thread.run(Thread.java:764)
` 

There is my implementation of service:
```
    @Override
    public int onStartCommand(Intent intent, int flags, int startId) {
        if (getString(R.string.action_start).equals(intent.getAction())) {
            startForeground();
            startVpn();
        }
        return super.onStartCommand(intent, flags, startId);
    }
    ParcelFileDescriptior vpnInterface;
    private void startVpn() {
          vpnInterface = create();
          alive = true;
         new Thread(this::vpnLoop).start();
    }
    private void vpnLoop() {
        try (FileChannel vpnIn = new FileInputStream(vpnInterface.getFileDescriptor()).getChannel();
             FileChannel vpnOut = new FileOutputStream(vpnInterface.getFileDescriptor()).getChannel()) {
            final JBBPParser ethernetParserHeaderWithout802_1QTag = JBBPParser.prepare(
                    "byte[6] MacDestination;"
                            + "byte[6] MacSource;"
                            + "ushort EtherTypeOrLength;"
            );
            // IPv4 header
            final JBBPParser ipParserHeaderWithoutOptions = JBBPParser.prepare(
                    "bit:4 InternetHeaderLength;"
                            + "bit:4 Version;"
                            + "bit:2 ECN;"
                            + "bit:6 DSCP;"
                            + "ushort TotalPacketLength;"
                            + "ushort Identification;"
                            + "ushort IPFlagsAndFragmentOffset;"
                            + "ubyte TTL;"
                            + "ubyte Protocol;"
                            + "ushort HeaderChecksum;"
                            + "int SourceAddress;"
                            + "int DestinationAddress;"
                            + "byte [(InternetHeaderLength-5)*4] Options;"
            );
            // TCP header
            final JBBPParser tcpHeader = JBBPParser.prepare(
                    "ushort SourcePort;"
                            + "ushort DestinationPort;"
                            + "int SequenceNumber;"
                            + "int AcknowledgementNumber;"
                            + "bit:1 NONCE;"
                            + "bit:3 RESERVED;"
                            + "bit:4 HLEN;"
                            + "bit:1 FIN;"
                            + "bit:1 SYN;"
                            + "bit:1 RST;"
                            + "bit:1 PSH;"
                            + "bit:1 ACK;"
                            + "bit:1 URG;"
                            + "bit:1 ECNECHO;"
                            + "bit:1 CWR;"
                            + "ushort WindowSize;"
                            + "ushort TCPCheckSum;"
                            + "ushort UrgentPointer;"
                            + "byte [$$-HLEN*4] Option;"
            );
            boolean dataSent = true;
            ByteBuffer readBuffer = null;
            while (alive) {
                if (dataSent) {
                    readBuffer = ByteBuffer.allocateDirect(BUFFER_SIZE);
                } else {
                    readBuffer.clear();
                }

                int readBytes = vpnIn.read(readBuffer);
                if (readBytes > 0) {
                    readBuffer.flip();
                    try (JBBPBitInputStream netPacketStream = new JBBPBitInputStream(new ByteArrayInputStream(readBuffer.array()))) {
                        // Check Ethernet header
                        final JBBPFieldStruct parsedEthernetHeader = ethernetParserHeaderWithout802_1QTag.parse(netPacketStream);
                        Log.i(TAG, "MAC DESTINATION: " + new String(parsedEthernetHeader
                                .findFieldForNameAndType("MacDestination", JBBPFieldArrayByte.class).getArray()));
                        Log.i(TAG, "MAC SOURCE: " + new String(parsedEthernetHeader
                                .findFieldForNameAndType("MacSource", JBBPFieldArrayByte.class).getArray()));
                        final int etherTypeOrLength = parsedEthernetHeader
                                .findFieldForNameAndType("EtherTypeOrLength", JBBPFieldUShort.class).getAsInt();
                        if (etherTypeOrLength > 1500) {
                            // list of protocols http://standards-oui.ieee.org/ethertype/eth.txt
                            System.out.println("Ethernet type is : 0x" + Integer.toHexString(etherTypeOrLength).toUpperCase());
                        } else {
                            System.out.println("Payload length : " + etherTypeOrLength);
                        }

                        // Check IP header
                        netPacketStream.resetCounter();
                        final JBBPFieldStruct parsedIPHeader = ipParserHeaderWithoutOptions.parse(netPacketStream);
                        Log.i(TAG, "IP VERSION: " + parsedIPHeader
                                .findFieldForNameAndType("Version", JBBPFieldBit.class).getAsInt());
                        final int internetHeaderLength = parsedIPHeader
                                .findFieldForNameAndType("InternetHeaderLength", JBBPFieldBit.class).getAsInt();
                        Log.i(TAG, "Length of the IP header (in 4 byte items)" + String.valueOf(internetHeaderLength));
                        Log.i(TAG, "DSCP: " + parsedIPHeader.findFieldForNameAndType("DSCP", JBBPFieldBit.class).getAsInt());
                        Log.i(TAG, "ECN: " + parsedIPHeader.findFieldForNameAndType("ECN", JBBPFieldBit.class).getAsInt());
                        final int ipTotalPacketLength = parsedIPHeader
                                .findFieldForNameAndType("TotalPacketLength", JBBPFieldUShort.class).getAsInt();
                        Log.i(TAG, "Entire IP packet size, including header and data, in bytes: " + String.valueOf(ipTotalPacketLength));
                        Log.i(TAG, "Identification: " + parsedIPHeader
                                .findFieldForNameAndType("Identification", JBBPFieldUShort.class).getAsInt());
                        final int ipFlagsAndFragmentOffset = parsedIPHeader
                                .findFieldForNameAndType("IPFlagsAndFragmentOffset", JBBPFieldUShort.class).getAsInt();
                        Log.i(TAG, "Extracted IP flags^ " + String.valueOf(ipFlagsAndFragmentOffset >>> 13));
                        Log.i(TAG, "Extracted Fragment offset: " + String.valueOf(ipFlagsAndFragmentOffset & 0x1FFF));
                        Log.i(TAG, "TTL: " + parsedIPHeader.findFieldForNameAndType("TTL", JBBPFieldUByte.class).getAsInt());
                        Log.i(TAG, "Protocol (RFC-790): " + parsedIPHeader
                                .findFieldForNameAndType("Protocol", JBBPFieldUByte.class).getAsInt());
                        Log.i(TAG, "IPv4 Header Checksum: " + parsedIPHeader
                                .findFieldForNameAndType("HeaderChecksum", JBBPFieldUShort.class).getAsInt());
                        Log.i(TAG, "Source IP Address: " + parsedIPHeader
                                .findFieldForNameAndType("SourceAddress", JBBPFieldInt.class).getAsInt());
                        Log.i(TAG, "Destination IP Address: " + parsedIPHeader
                                .findFieldForNameAndType("DestinationAddress", JBBPFieldInt.class).getAsInt());
                        Log.i(TAG, "Options: " + parsedIPHeader.findFieldForNameAndType("Options", JBBPFieldArrayByte.class).getArray().length);

                        // Check TCP header
                        netPacketStream.resetCounter();
                        final JBBPFieldStruct parsedTcpHeader = tcpHeader.parse(netPacketStream);
                        Log.i(TAG, "Source Port: " + parsedTcpHeader.findFieldForNameAndType("SourcePort", JBBPFieldUShort.class).getAsInt());
                        Log.i(TAG, "Destination Port: " + parsedTcpHeader.findFieldForNameAndType("DestinationPort", JBBPFieldUShort.class).getAsInt());
                        Log.i(TAG, "Sequence number: " + parsedTcpHeader.findFieldForNameAndType("SequenceNumber", JBBPFieldInt.class).getAsInt());
                        Log.i(TAG, "Acknowledgement number: " + parsedTcpHeader.findFieldForNameAndType("AcknowledgementNumber", JBBPFieldInt.class).getAsInt());
                        Log.i(TAG, "FIN: " + parsedTcpHeader.findFieldForNameAndType("FIN", JBBPFieldBit.class).getAsBool());
                        Log.i(TAG, "SYN: " + parsedTcpHeader.findFieldForNameAndType("SYN", JBBPFieldBit.class).getAsBool());
                        Log.i(TAG, "RST: " + parsedTcpHeader.findFieldForNameAndType("RST", JBBPFieldBit.class).getAsBool());
                        Log.i(TAG, "PSH: " + parsedTcpHeader.findFieldForNameAndType("PSH", JBBPFieldBit.class).getAsBool());
                        Log.i(TAG, "ASK: " + parsedTcpHeader.findFieldForNameAndType("ACK", JBBPFieldBit.class).getAsBool());
                        Log.i(TAG, "URG: " + parsedTcpHeader.findFieldForNameAndType("URG", JBBPFieldBit.class).getAsBool());
                        Log.i(TAG, "ECNECHO: " + parsedTcpHeader.findFieldForNameAndType("ECNECHO", JBBPFieldBit.class).getAsBool());
                        Log.i(TAG, "CWR: " + parsedTcpHeader.findFieldForNameAndType("CWR", JBBPFieldBit.class).getAsBool());
                        Log.i(TAG, "NONCE: " + parsedTcpHeader.findFieldForNameAndType("NONCE", JBBPFieldBit.class).getAsBool());
                        Log.i(TAG, "RESERVED: " + parsedTcpHeader.findFieldForNameAndType("RESERVED", JBBPFieldBit.class).getAsBool());
                        Log.i(TAG, "HLEN: " + parsedTcpHeader.findFieldForNameAndType("HLEN", JBBPFieldBit.class).getAsInt());
                        Log.i(TAG, "Window Size: " + parsedTcpHeader.findFieldForNameAndType("WindowSize", JBBPFieldUShort.class).getAsInt());
                        Log.i(TAG, "TCP Checksum: " + parsedTcpHeader.findFieldForNameAndType("TCPCheckSum", JBBPFieldUShort.class).getAsInt());
                        Log.i(TAG, "URGENT POINTER: " + parsedTcpHeader.findFieldForNameAndType("UrgentPointer", JBBPFieldUShort.class).getAsInt());
                        Log.i(TAG, "OPTION: " + parsedTcpHeader.findFieldForNameAndType("Option", JBBPFieldArrayByte.class).size());

                        // extract data
                        final int payloadDataLength = ipTotalPacketLength - (internetHeaderLength * 4) - (int) netPacketStream.getCounter();
                        final byte[] data = netPacketStream.readByteArray(payloadDataLength);

                        Log.i(TAG, new JBBPTextWriter(new StringWriter()).Comment("Payload data extracted from the TCP part").Byte(data).BR().toString());

                        byte[] restOfFrame = netPacketStream.readByteArray(-1);
                        Log.i(TAG, "REST OF FRAME: " + restOfFrame.length);
                    }

                } else {
                    dataSent = false;
                }


                if (!dataSent)
                    Thread.sleep(10);

                //TODO: data receive
            }
        } catch (IOException | InterruptedException e) {
            e.printStackTrace();
        }
    }
```

Thank you, and please, help me.

**Comment by raydac** [comment]
it looks like that calculation just generates negative size because 
InternetHeaderLength < 5, so that expresion can be corrected to support 
such situation

byte 
[((InternetHeaderLength-5)*4)*((((InternetHeaderLength-5)&16)^16)>>4)] 
Options;

-- 
Igor Maznitsa

email: rrg4400@gmail.com
http://www.igormaznitsa.com
